### PR TITLE
DTO to EMF converters

### PR DESCRIPTION
**Pull request by ideas-into-software**
- DTO to EPackage converter ( https://github.com/geckoprojects-org/org.gecko.emf.utils/issues/51 )
  
 - Converter Impl for DTO to EObject ( https://github.com/geckoprojects-org/org.gecko.emf.utils/issues/52 ) - skeleton

## DTO to EPackage converter

 - Support for all types as defined in section "57.2 Data Transfer Object" of "Data Transfer Objects Specification" ( https://docs.osgi.org/specification/osgi.core/8.0.0/framework.dto.html#d0e48285 ), i.e.: 
 
   * Primitive types
 
   * Wrapper classes for the primitive types

   * String

   * enum

   * Version (`org.osgi.framework.Version`)

   * Data Transfer Objects

   * List

   * Set

   * Map

   * array

 - Conversion of Set is implemented as per info shared by Mr. Ed Merks in "How to create a HashSet with EMF?" ( https://www.eclipse.org/forums/index.php?t=msg&th=134711&goto=421887&, i.e. (...) There's no direct support for that. (...) All EObject-containing lists currently don't allow duplicates either, so they have do have set-like behavior. (...)

### Questions

 1. OSGi Component or util class ( like currently, and as defined in specs for https://github.com/geckoprojects-org/org.gecko.emf.utils/issues/51 ) ? 
 
 2. If util class, dedicated bundle ( `org.gecko.emf.converter` ) or existing, e.g `org.gecko.emf.util.common` ?
 
 3. If util class, prefer class or enum type like currently, as per "Effective Java" by Joshua Bloch "Item 3: Enforce the singleton property with a private constructor or an enum type" ?

 4. Validation - i.e. validate if classes passed to `org.gecko.emf.converter.DTOToEPackageConverter.convert(String, String, String, Class<? extends DTO>...)` meet DTO specification ?

### More info

 - "57 Data Transfer Objects Specification - OSGi Core 8"
    https://docs.osgi.org/specification/osgi.core/8.0.0/framework.dto.html

 - "Teneo/Hibernate/Dynamic EMF Tutorial"
    https://wiki.eclipse.org/Teneo/Hibernate/Dynamic_EMF_Tutorial

 - "CHAPTER 2: 2.5.4 Dynamic EMF"
    https://d3s.mff.cuni.cz/legacy/~gergic/presentations/emf/resources/budinskych02.pdf

 - "Fundamentals of the Eclipse Modeling Framework: Dynamic EMF"
    https://eclipse.dev/modeling/emf/docs/presentations/EclipseCon/EclipseCon2008_309T_Fundamentals_of_EMF.pdf

 - "Discover the Eclipse Modeling Framework (EMF) and Its Dynamic Capabilities"
    https://www.devx.com/java-zone/29093/

 - "How to create a HashSet with EMF?"
    https://www.eclipse.org/forums/index.php?t=msg&th=134711&goto=421887&

## Converter Impl for DTO to EObject

In this stage, focus was on `org.gecko.emf.converter.DTOToEPackageConverter` ( see earlier section ). Pending clarification of following questions, `org.gecko.emf.converter.DTOToEObjectConverterImpl` remains as skeleton.

### Questions

 1. Should all 3 methods defined on `org.osgi.util.converter.Converter` be implemented ? i.e. in addition to `org.osgi.util.converter.Converter.convert(Object)`, there is `org.osgi.util.converter.Converter.newConverterBuilder()` and `org.osgi.util.converter.Converter.function()`

### CODE REVIEW

**Comment by ideas-into-software** [comment]
@juergen-albert Please see commit https://github.com/geckoprojects-org/org.gecko.emf.utils/pull/54/commits/1129864c486f7a3c839a34bb42f9a5ea5b87ede2 and info shared via https://github.com/geckoprojects-org/org.gecko.emf.utils/pull/54#issue-2242265304, most importantly questions posted.

**Comment by juergen-albert** [comment]
What you have so far looks good to me. Minor Change Requests follow at the end of this comment.

# Answer to Questions

> OSGi Component or util class?

If you don't need injected services, a Util Class should be sufficient.

> If util class, dedicated bundle ( org.gecko.emf.converter ) or existing, e.g org.gecko.emf.util.common ?

org.gecko.emf.converter Bundle is okay. 

> If util class, prefer class or enum type like currently, as per "Effective Java" by Joshua Bloch "Item 3: Enforce the singleton property with a private constructor or an enum type" 

private Constructor with singleton INSTANCE variable works for me.

> Validation

What you did should work for some POJOs as well. So I think we don't need to be as strict here and you can open it up to `Class<?>`

> Should all 3 methods defined on org.osgi.util.converter.Converter be implemented ? i.e. in addition to org.osgi.util.converter.Converter.convert(Object), there is org.osgi.util.converter.Converter.newConverterBuilder() and org.osgi.util.converter.Converter.function()

I believe `convert` and `function` are both required, so the Converter works properly. `newConverterBuilder` would be nice, to have a preconfigured builder for the Converter available.

# Change Requests

1. A while back (during the time of the Exporter) I had to work some git magic, to fix the broken commits that trip the DCO check. This is why,  the PR has so many commits and why  your commit is on the bottom of the list. To fix this, I suggest: Do a clean checkout of the repository and copy the two new bundles in your fresh repository. With this you can do the commit again and all should hopefully be fine.

2. DTOToEPackageConverter Line 120 - Please don't put the created Package in the Registry. This should be the decision of the user of the convert method.
3.  Please move the Datatypes you create in the static Block to fill the JAVATYPE_TO_EDATATYPE Map to a separate Model with an ecore and generated code. Right now, the Datatypes are not contained (from an EMF perspective) anywhere. When you want to save the resulting EPackage, the Datatypes will not be referenced correctly in the resulting file. Additionally, I believe they can be reused in the future.
4. Instead of adding each DataType manually in your static block you can do something like:
```
EcorePackage.eINSTANCE.getEClassifiers().stream()
			.filter(EDataType.class::isInstance)
			.map(EDataType.class::cast)
			.forEach(dt -> JAVATYPE_TO_EDATATYPE.put(dt.getInstanceClass(), dt));
```

**Comment by ideas-into-software** [comment]
@juergen-albert

Thank you for the feedback. 

Answers to questions I asked - all clear.

Your change requests - mostly clear, except for items no.3 and no.4, i.e.:

#### RE: no.3 "Please move the Datatypes you create (...)"
 
 * The static block you're referring to maps built-in Java types to `EDataType`s;
 
 * Those are mostly EMF's built-in `EDataType`s (i.e. `String.class` -> `EcorePackage.eINSTANCE.getEString()`), but also custom `EDataType`s - those however are also using built-in Java types; 
 
 * One exception is `org.osgi.framework.Version`, but if someone is using that `org.osgi.framework.Version` as field type in DTOs passed, they must have access to bundle which provides this class;
 
 * Currently, they are set only via `setEType` on `EAttribute` / `EReference` during processing - it is true they are not added via dynamically-generated `EPackage` yet;
 
 * Wouldn't it be easier to simply add these custom `EDataType`s (i.e. all which are not EMF's built-ins, i.e. those created via `private static EDataType create*EDataType()` methods) to this dynamically-generated `EPackage` via `dynamicEPackage.getEClassifiers().add(custom_EDataType)` ?
 
 * If you still insist on adding a separate EMF model, this model would exist in a separate bundle ( e.g. `org.gecko.emf.converter.model` ) and be referenced from `org.gecko.emf.converter`, then `EPackage` containing such custom `EDataType`s imported and these used this way ( a la `org.gecko.emf.pushstream.PushStreamPackage` and `EDataType getEPushStream()` - one of the custom `EDataType`s defined in `/org.gecko.emf.pushstreams/model/pushstream.ecore` ) ?


#### RE: no.4 "Instead of adding each DataType manually (...)"

 * This would probably make sense only if using such separate generated `EPackage` as referred to in no.3 above, i.e. I could dynamically add EMF's built-in `EDataType`s AND those custom `EDataType`s - using approach you suggested here in no.4; 
 
 * Please clarify then regarding no.3 and I will proceed accordingly;

**Comment by juergen-albert** [comment]
> RE: no.3 "Please move the Datatypes you create (...)"

The Topic is a bit more complex, so it is hard to simply respond to your individual points. So, first a bit of context.
EMF works with models that can work with loaded and generated code. Both can work together, regardless if your generated code references code that is loaded from a file or the other way around. When you create an EPackage that has a class with a an attribute of type EString as an ecore, you will see in the core file find in the file and xml attribute  'eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"'. This points to the EDataType EString in the package with the URI  http://www.eclipse.org/emf/2002/Ecore. When the file is loaded, it looks in the end for a `Resource` with the URI `http://www.eclipse.org/emf/2002/Ecore` and calls `Resource.getEObject` with the URI fragment `//EString`, which will produce the EDataType `EString`. 
At Runtime, EMF can work fine with Java Refernces. The Goal of the EPackage (and any EMF Classes we create programticaly), must and usually will be, that we serialize it with emf. Thus, if we want to save the resulting EPackage, it will result ins something like: `eType="ecore:EDataType <YourDataTypeName>"' . <YourDataTypeName> will have nor URI like http://somePackageUri or something, to give EMF a hint, where to find the resource to load the Datatype from. Thus it needs to be contained in something that has a resource. In this case, it should be an EPackage. 
Sidenote, EMF has a pretty sophisticated mechanism to translate between Resource URIs and mix stuff loaded from Files with generated code, as it makes no difference from an EMF perspective.

Back to your suggestions: 

* Adding the DataTypes to the generated EPackage is not a good option. If we would generate the EPackages for 2 different sets of DTOs would result in 2 Copies of the same custom Datatypes, that would never match from an EMF perspective. It would in the end be like String class loaded from 2 different Classloaders. 
* Moving them to a sperate model bundle, is therefore a good solution, as we can reuse them elsewhere as well. 

> RE: no.4 "Instead of adding each DataType manually (...)"

Given my explanation above, I hope this makes sense now. My code snippet from above for `EcorePackage` and for whatever package you come up with, will always make all modeled DataTypes available, without any additional work (given, that I haven't overlooked any code, that goes further than a lookup in the map).

**Comment by ideas-into-software** [comment]
## Converter Impl for DTO to EObject

One of the requirements was to implement all 3 methods defined on the `org.osgi.util.converter.Converter` interface ( i.e `org.osgi.util.converter.Converter.convert(Object)`, `org.osgi.util.converter.Converter.newConverterBuilder()` and `org.osgi.util.converter.Converter.function()` ). 

However, since this required significant rework of existing `org.osgi.util.converter.Converter` implementation, an alternative solution based on standard (existing) `org.osgi.util.converter.Converter` implementation is also provided - see test cases in `org.gecko.emf.converter.tests.DTOToEObjectConverterImplTest` for details, i.e.: 
 
  1. `org.gecko.emf.converter.tests.DTOToEObjectConverterImplTest.testDTO2EObjectConverterWithBuiltInFunction()` - based on custom `org.osgi.util.converter.Converter` implementation, including custom implementation of `org.osgi.util.converter.ConverterFunction` to convert DTOs to EObjects;
 
  2. `org.gecko.emf.converter.tests.DTOToEObjectConverterImplTest.testDTO2EObjectConverterWithBuiltInTypeRule()` - based on custom `org.osgi.util.converter.Converter` implementation, including custom implementation of `org.osgi.util.converter.TypeRule` to convert DTOs to EObjects;
 
  3.  `org.gecko.emf.converter.tests.DTOToEObjectConverterImplTest.testStandardConverterWithDTO2EObjectConverterFunction()` - based on standard (existing) `org.osgi.util.converter.Converter` implementation, with custom implementation of `org.osgi.util.converter.ConverterFunction` to convert DTOs to EObjects simply added to `org.osgi.util.converter.ConverterBuilder` ( `org.osgi.util.converter.ConverterBuilder.rule(ConverterFunction)` );
 
  4. `org.gecko.emf.converter.tests.DTOToEObjectConverterImplTest.testStandardConverterWithDTO2EObjectTypeRule()` - based on standard (existing) `org.osgi.util.converter.Converter` implementation, with custom implementation of `org.osgi.util.converter.TypeRule` to convert DTOs to EObjects simply added to `org.osgi.util.converter.ConverterBuilder` ( `org.osgi.util.converter.ConverterBuilder.rule(TargetRule)` );


Please note that using custom `org.osgi.util.converter.Converter` implementation will require releasing new version of `org.osgi.util.converter` - release of such new, refactored version ( 1.1.0 ), is temporarily included in `Local` repository.


### Questions (c.d.)

 1. Should `DTOToEPackageConverter` be in the same bundle as `DTOToEObjectConverter*` classes or moved to separate bundles ? If separate bundles, any naming preference ? ( e.g. `org.gecko.emf.converter.dto_to_eobject`, `org.gecko.emf.converter.dto_to_epackage` )

**Comment by ideas-into-software** [comment]
@juergen-albert Please familiarize yourself with this latest commit ( https://github.com/geckoprojects-org/org.gecko.emf.utils/pull/54/commits/a3d376757bfd082d510e1a1a7f2216cebd6f4bd5 ) - please see above comment ( https://github.com/geckoprojects-org/org.gecko.emf.utils/pull/54#issuecomment-2076021591 ) for more details. 

In the meantime, I will take care of changes you requested for https://github.com/geckoprojects-org/org.gecko.emf.utils/issues/51, discussed several days ago.

**Pull request closed without merging**
