### PR TITLE
Replaced FastODS with SODS

### PR DESCRIPTION
**Pull request by ideas-into-software**
@juergen-albert @stbischof

As per request, due to licensing issue with FastODS, I have replaced it with SODS (https://github.com/miachm/SODS). 
Except for features which SODS is currently missing, everything works as with previous version. 

Missing features are: 
 - no CRLF character support in cell for values which must be output on separate lines; in cells where multiple reference IDs are output this becomes one long string – equivalent of FastODS’s `TextBuilder` / `Paragraph` must be added to SODS, or at least respecting CRLF and outputting such on new lines;
  - no links
  - no ability to freeze row

SODS library was wrapped and added to local repository as there is no release version yet with proper OSGi manifest headers.

I’ve noticed Stefan is working on SODS project – there was a recent pull request from Stefan merged into SODS (https://github.com/miachm/SODS/commits/master). Are you perhaps working on adding those missing features to SODS or should I take care of this?

### CODE REVIEW

**Comment by ideas-into-software** [comment]
@juergen-albert @stbischof

 - Added support for links after having added this new feature to SODS library (see https://github.com/miachm/SODS/pull/63)
 
 - Added support for mapping tables
 
 - Various fixes & improvements 

Attached please find examples of generated ODS files - those three cases are explained in their file names. 

Please clarify if having links compatible with Excel (please verify yourself - ODS files attached) still requires a separate exporter for Excel, or this is sufficient. 

[testBasicPackageExport11684183219405744071.addMappingTable-disabled&generateLinks-enabled.ods](https://github.com/geckoprojects-org/org.gecko.emf.utils/files/11094232/testBasicPackageExport11684183219405744071.addMappingTable-disabled.generateLinks-enabled.ods)
[testBasicPackageExport2348042832616144705.addMappingTable-enabled&generateLinks-disabled.ods](https://github.com/geckoprojects-org/org.gecko.emf.utils/files/11094233/testBasicPackageExport2348042832616144705.addMappingTable-enabled.generateLinks-disabled.ods)
[testBasicPackageExport13762410703655588523.addMappingTable-enabled&generateLinks-enabled.ods](https://github.com/geckoprojects-org/org.gecko.emf.utils/files/11094234/testBasicPackageExport13762410703655588523.addMappingTable-enabled.generateLinks-enabled.ods)

**Comment by ideas-into-software** [comment]
@juergen-albert @stbischof

Merge conflicts are resolved now, ready to merge.

Please clarify: 

1.  If having links compatible with Excel (please verify yourself - ODS files attached) still requires a separate exporter for Excel, or this is sufficient
2. Metadata related - if and how documentation @ type level should be handled (currently at field level only).
3. Whether a separate CSV exporter is required - as discussed during 2023/01/31 meeting with @juergen-albert

**Comment by juergen-albert** [comment]
> Metadata related - if and how documentation @ type level should be handled (currently at field level only).

In the attached ODS, I added an example of how I think it could look like for the Family Metadata.
[testBasicPackageExport11684183219405744071.addMappingTable-disabled.generateLinks-enabled.ods](https://github.com/geckoprojects-org/org.gecko.emf.utils/files/11249162/testBasicPackageExport11684183219405744071.addMappingTable-disabled.generateLinks-enabled.ods)

**Comment by ideas-into-software** [comment]
@juergen-albert "Metadata documentation improvements" commit contains required changes. 

Attaching generated ODS files. There are two models used in the integration test - one of them, `org.gecko.emf.osgi.example.model.basic` does not have any documentation annotations.

[testBasicPackageExport5213785929955836613.no-metadata-docs-in-model.ods](https://github.com/geckoprojects-org/org.gecko.emf.utils/files/11266569/testBasicPackageExport5213785929955836613.no-metadata-docs-in-model.ods)
[testUtilitiesPackageExport10368667694391926136.metadata-docs-in-model.ods](https://github.com/geckoprojects-org/org.gecko.emf.utils/files/11266570/testUtilitiesPackageExport10368667694391926136.metadata-docs-in-model.ods)

**Pull request merged**
