### PR TITLE
Jakarta-Javax split

### PR DESCRIPTION
**Pull request by ideas-into-software**
https://github.com/geckoprojects-org/org.gecko.emf.utils/issues/25

### CODE REVIEW

**Comment by juergen-albert** [comment]
@ideas-into-software can you take a look into the build error, so we can get this ready to merge and release?

**Comment by ideas-into-software** [comment]
> @ideas-into-software can you take a look into the build error, so we can get this ready to merge and release?

@juergen-albert Yes, sure. Before merge and release, however, following must be addressed: https://github.com/geckoprojects-org/org.gecko.emf.utils/issues/25#issuecomment-1800077188

**Comment by ideas-into-software** [comment]
@juergen-albert

All issues which I could replicate locally were resolved and fixes committed. 

Additional problems arose in GitHub Workflow 'Sonar' - first was `Metaspace` `OutOfMemoryError` exception; that one was fixed by increasing amount of metaspace memory to 512m.

However, 'Sonar' workflow still fails due to wrong version of `org.gecko.emf.exporter.ods` bundle being resolved in `org.gecko.emf.exporter.ods.tests/test.bndrun` - i.e. `1.0.1`, instead of `1.0.2`.. 

Both resolution and all tests are passing correctly when run locally, off same files as those committed and used in 'Sonar' workflow.. Not sure what else could be done except to "freeze" local resolution of `org.gecko.emf.exporter.ods.tests/test.bndrun` and commit such. Do you have any other ideas?

Screenshot from 2023-11-10 00-57-03
Screenshot from 2023-11-10 02-28-01
Screenshot from 2023-11-10 02-29-43

**Comment by juergen-albert** [comment]
For some reason, the sonar build seems to use the dependencies from the basline repo (which seems to contain the older version). 

The other thing I ask myself here: why does he run the tests. If I read the build log correctly it should skip the tests because it is started with `./gradlew build sonarqube -x test -x testOSGi --info --stacktrace`.

**Comment by juergen-albert** [comment]
Okay, the tests a run, because the task is named itest and not test and testOSGi. I guess you can skip this here as well, because the tests run the in the other build steps as well.

**Pull request merged**
