### PR TITLE
Gecko EMF CSV Exporter

### PR DESCRIPTION
**Pull request by ideas-into-software**
- Support for exporting EMF resources and lists of EMF objects to CSV format in ZIP mode

 - Refactor of format-agnostic parts / common to all formats

 - Refactor of format-specific parts

### CODE REVIEW

**Comment by ideas-into-software** [comment]
@juergen-albert

In this PR you will find CSV exporter for ZIP mode - it takes less than 6 seconds total to process `CityTree.xmi` you provided, where actual writing of CSV files and ZIP archive takes less than 1 second (i.e. all 4 types, including those 3 distinct types of 42000+ records each).

For flat mode CSV, please need more advanced / less trivial examples - i.e. for models like `CityTree`, how should such flat CSV look like ? How should it look like for `org.gecko.emf.osgi.example.model.basic` model (see `org.gecko.emf.ods.tests.EMFODSExporterTest` where this model is used) ?

**Comment by juergen-albert** [comment]
As an Example for the Flat Mode, we have the following assumed model: 

Family:
 - id : String
 - mother: Person
 - father: Person
 - children : Person{*]
 
 Person: 
 - id
 - name

For the Family Simpons the header for a flat cxv would be

```
id, mother.id, mother.name, father.id, father.name, children.0.id, children.0.name, children.1.id, children.1.name, children.2.id, children.2.name
```

If the Children would be non Containments the headers should looks as follows:

```
id, mother.id, mother.name, father.id, father.name, children.0.eProxyUri, children.1.eProxyUri, children.2.eProxyUri
```

**Comment by ideas-into-software** [comment]
@juergen-albert 

This example you provided in previous comment is very similar to what you already mentioned in https://github.com/geckoprojects-org/org.gecko.emf.utils/issues/14#issue-1851462447. 

I need to see how you imagine handling much more complex cases, like in files I sent you via email - re-attaching those; especially 'testBasicPackageExport1685993983081426336.ods' - please base your answer on this, if possible.

Also, as discussed during our recent call, what about situations where there are one-to-many mappings, with tenths of such references? We'd end up with CSV file with hundred+ headers..


[testExportUtilitiesPackageEObjectsToCsvZipMode13827390835329554056.zip](https://github.com/geckoprojects-org/org.gecko.emf.utils/files/12542081/testExportUtilitiesPackageEObjectsToCsvZipMode13827390835329554056.zip)

[testSaveResourceToCsvZipMode12448981008303159044.zip](https://github.com/geckoprojects-org/org.gecko.emf.utils/files/12542083/testSaveResourceToCsvZipMode12448981008303159044.zip)

[treesPackageExportEObjectsToTest5008897003768925270.zip](https://github.com/geckoprojects-org/org.gecko.emf.utils/files/12542078/treesPackageExportEObjectsToTest5008897003768925270.zip)

[testBasicPackageExport1685993983081426336.ods](https://github.com/geckoprojects-org/org.gecko.emf.utils/files/12542086/testBasicPackageExport1685993983081426336.ods)

[treesPackageExportEObjectsToTest7945267940228904456.xlsx](https://github.com/geckoprojects-org/org.gecko.emf.utils/files/12542091/treesPackageExportEObjectsToTest7945267940228904456.xlsx)

**Comment by juergen-albert** [comment]
I'm not 100% sure what specifically is unclear to you. Thus I will define the constraints with which I look at the flat mode (will apply to ODS/Excel as well):

* The List of EObjects given to the exporter define the root objects
* The list of objects MUST all be of the same EClass or inherit from the same base EClass (at least above EObject)
* As it may get to complicated when the Classes diverge too much, you may also define a constraint that all EClasses must follow just one lineage (Family -> ExtendedFamily -> BasedUponExtenededFamily: OK; Family->ExndedFamily + Family->SomethingBasedOnFamily: NOT OK)
* We should define a limit on the amount of headers allowed (maybe configurable). We could set the default to what Excel supports, as most users of a csv export will likely use it with that. The Limit I found is 16,384 for that.

Does this help?

**Comment by ideas-into-software** [comment]
Superseded by https://github.com/geckoprojects-org/org.gecko.emf.utils/pull/23

**Pull request closed without merging**
